### ISSUE TITLE
Profile information REST API

### ISSUE THREAD

**Issue by GiovannaTheo** [unige-pinfo-2018/PInfo1-backend#6]
It would be useful to have some REST api that allow us to retrieve user information (name, age, university, degree, bla-bla-bla). Of course we also need to have setters in place.

That way, @kilian-ruchti will be able to link is Profile component to the backend code through REST requests, in order to display correct information. 

For the profile picture, this should be handled by the Imgur API. Maybe store in the DB the link to the profile pic ?

**Comment by arthurdeschamps** [comment]
Well there are the `getUser` methods (and soon `getUserByEmail`). Isn't that enough ?

**Comment by GiovannaTheo** [comment]
Should be, indeed. What exact fields are available to us in the DB ? Name, age, university, degree... ?

**Comment by arthurdeschamps** [comment]
```USERNAME, EMAIL, ROLE, CURSUS, CONFIRMED```
on the current version.

Password is "blurred".
